var T=Object.defineProperty,L=Object.defineProperties;var k=Object.getOwnPropertyDescriptors;var v=Object.getOwnPropertySymbols;var A=Object.prototype.hasOwnProperty,C=Object.prototype.propertyIsEnumerable;var O=(t,n,c)=>n in t?T(t,n,{enumerable:!0,configurable:!0,writable:!0,value:c}):t[n]=c,g=(t,n)=>{for(var c in n||(n={}))A.call(n,c)&&O(t,c,n[c]);if(v)for(var c of v(n))C.call(n,c)&&O(t,c,n[c]);return t},j=(t,n)=>L(t,k(n));(function(t,n){typeof exports=="object"&&typeof module!="undefined"?module.exports=n(require("react")):typeof define=="function"&&define.amd?define(["react"],n):(t=typeof globalThis!="undefined"?globalThis:t||self,t["react-lazy-img"]=n(t.React))})(this,function(t){"use strict";function n(e){return e&&typeof e=="object"&&"default"in e?e:{default:e}}var c=n(t),p={exports:{}},l={};/*
object-assign
(c) Sindre Sorhus
@license MIT
*/var d=Object.getOwnPropertySymbols,_=Object.prototype.hasOwnProperty,h=Object.prototype.propertyIsEnumerable;function w(e){if(e==null)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(e)}function E(){try{if(!Object.assign)return!1;var e=new String("abc");if(e[5]="de",Object.getOwnPropertyNames(e)[0]==="5")return!1;for(var r={},o=0;o<10;o++)r["_"+String.fromCharCode(o)]=o;var f=Object.getOwnPropertyNames(r).map(function(s){return r[s]});if(f.join("")!=="0123456789")return!1;var a={};return"abcdefghijklmnopqrst".split("").forEach(function(s){a[s]=s}),Object.keys(Object.assign({},a)).join("")==="abcdefghijklmnopqrst"}catch{return!1}}E();/** @license React v17.0.2
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var x=c.default,b=60103;if(l.Fragment=60107,typeof Symbol=="function"&&Symbol.for){var m=Symbol.for;b=m("react.element"),l.Fragment=m("react.fragment")}var P=x.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,S=Object.prototype.hasOwnProperty,R={key:!0,ref:!0,__self:!0,__source:!0};function y(e,r,o){var f,a={},s=null,u=null;o!==void 0&&(s=""+o),r.key!==void 0&&(s=""+r.key),r.ref!==void 0&&(u=r.ref);for(f in r)S.call(r,f)&&!R.hasOwnProperty(f)&&(a[f]=r[f]);if(e&&e.defaultProps)for(f in r=e.defaultProps,r)a[f]===void 0&&(a[f]=r[f]);return{$$typeof:b,type:e,key:s,ref:u,props:a,_owner:P.current}}l.jsx=y,l.jsxs=y,p.exports=l;const I=p.exports.jsx;var N=e=>{const r=t.useRef(null);return t.useEffect(()=>{var f;(f=r.current)==null||f.setAttribute("data-src",e.src);const o=new IntersectionObserver(a=>{a.forEach(s=>{if(s.isIntersecting){const u=s.target,i=u.getAttribute("data-src");u.setAttribute("src",i),o.unobserve(u)}})});o.observe(r.current)},[]),I("img",j(g({},e),{src:void 0,ref:r}))};return N});
